### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by QuLogic** [Calysto/metakernel#135] opened 2017-03-12 03:30 UTC
I'm not really sure how to get these to be reproducible, but I've been running tests a lot, and every once in a while, one or two tests will fail. Here are the results when they do:
```
======================================================================
FAIL: test_multiline (metakernel.tests.test_replwrap.REPLWrapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/metakernel-0.19.1/metakernel/tests/test_replwrap.py", line 35, in test_multiline
    self.assertEqual(res.strip().splitlines(), ['1 2', '3 4'])
AssertionError: Lists differ: [u"echo '1 2", u"3 4'", u'1 2'... != ['1 2', '3 4']

First differing element 0:
u"echo '1 2"
'1 2'

First list contains 2 additional elements.
First extra element 2:
u'1 2'

- [u"echo '1 2", u"3 4'", u'1 2', u'3 4']
+ ['1 2', '3 4']

======================================================================
FAIL: metakernel.tests.test_metakernel.test_ls_path_complete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/metakernel-0.19.1/metakernel/tests/test_metakernel.py", line 86, in test_ls_path_complete
    assert comp['matches'] == ['ipython/'], comp
AssertionError: {'matches': [u'"ls', u'-cdfa', u'compgen', 'ipython/', u'~/.ipytho"'], 'status': 'ok', 'cursor_start': 8, 'cursor_end': 14}
```

**Comment by has2k1** [comment] 2017-03-12 08:54
I have run into issues with tests running on Travis for OSX builds where the issue is an old version of bash. But I would assume if that is the case for you, the failures would be consistent.

**Comment by blink1073** [comment] 2017-03-12 10:14
I'm not sure what to fix here without being able to reproduce locally or on our CI builds, happy to accept patches.

**Comment by QuLogic** [comment] 2017-03-13 08:01
Yea, sorry I can't be more helpful, but hopefully someone might recognize something eventually.

**Comment by dsblank** [comment] 2017-04-23 12:22
Closing due to lack of reproducibility. But, as noted, perhaps someone will recognize, reopen, and fix. Thanks!

**Closed by dsblank** 2017-04-23 12:22 UTC
