### ISSUE TITLE
truncated and missing output with metakernel_bash

### ISSUE THREAD

**Issue by michaelsbradleyjr** [Calysto/metakernel#91] opened 2016-02-02 18:22 UTC
I'm running the latest metakernel / metakernel_bash (installed with pip) on jupyter and Python 3 (installed with miniconda2), on Mac OS X version 10.11.3.

Long running commands in a metakernel_bash notebook don't have their output displayed at all, and commands that generate multiple lines of output (and then exit) have only the last line displayed in their output cells.

I looked at several fairly recent commits and pull requests in this repo related to command output, and confirmed those changes are present in the metakernel python sources pip installed for me. So at this point, I'm not sure what's going wrong nor how to debug it.

**Comment by blink1073** [comment] 2016-02-04 14:56
Hi @michaelsbradleyjr, I'll have a look at this over the weekend.

**Comment by blink1073** [comment] 2016-02-06 16:32
Fixed by 82bbd037229a7d83860c018397e94b185afff37a and released in 0.12.3.

**Comment by blink1073** [comment] 2016-02-06 16:32
Can you verify?

**Comment by michaelsbradleyjr** [comment] 2016-02-06 16:41
Yes, both problems are fixed:  output is no longer truncated, and long-running commands have their output displayed continuously.

It may not be a bug (i.e. it may be a known limitation, I'm not sure), but if I issue a long-running command, such as:

`while true; do echo "hello"; sleep 1; done`

No other cells can generate output while it is running.

**Comment by blink1073** [comment] 2016-02-06 16:43
Not a bug, there is only one bash session running.

**Comment by michaelsbradleyjr** [comment] 2016-02-06 16:45
Ah right, makes sense.

**Comment by blink1073** [comment] 2016-02-06 21:08
I'll close it, thanks for the report!

**Closed by blink1073** 2016-02-06 21:08 UTC
